version: "3.4"
services:
  web:
    image: ghcr.io/smartstore/smartstore-linux
    container_name: web
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./appdata:/app/App_Data/Tenants
      - /var/www/smartstore/media:/app/wwwroot/media
  db:
    image: mysql:8
    container_name: mysql
    environment:
      #MYSQL_DATABASE: smartstore
      #MYSQL_USER: "root"
      MYSQL_PASSWORD: "TuMercappDb!"
      MYSQL_ROOT_PASSWORD: "TuMercappDb!"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
